deployments:
- nameOverride: react-app-deployment
  namespace: default
  labels:
    app: react-app
  image: sumanthhegde/jenkins:147
  imagePullPolicy: Always
  replicaCount: 2
  containerPort: 9000
services:
- nameOverride: react-app-service
  namespace: default
  type: LoadBalancer
  labels:
    app: react-app
  selector:
    app: react-app
  targetPort: 9000
  nodePort: 30003
