deployments:
- nameOverride: react-app-deployment
  namespace: default
  labels:
    app: react-app
  image: sumanthhegde/jenkins:153
  imagePullPolicy: Always
  replicaCount: 2
  containerPort: 80
services:
- nameOverride: react-app-service
  namespace: default
  type: LoadBalancer
  labels:
    app: react-app
  selector:
    app: react-app
  targetPort: 80
  nodePort: 31000
