apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$.Values.name}}-deployment
spec:
  selector:
    matchLabels:
      app: {{$.Values.name}}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{$.Values.name}}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{$.Values.name}}
        image: {{$.Values.image}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ default "8000" $.Values.port}}
