{{range .Values.deployments}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{default $.Release.Name .nameOverride }}
  namespace: {{default "'default" .namespace }}   
  labels:
    {{- include "mychart.labels" .labels | indent 4}}
spec:
  replicas: {{ default 1 .replicaCount }}
  selector:
    matchLabels:
      {{- include "mychart.labels" .labels | indent 6}}
  template:
    metadata:
      labels:
        {{- include "mychart.labels" .labels | indent 8}}
    spec:
      containers:
      - name: {{ default $.Release.Name .nameOverride}}  
        image: {{ .image }}
        imagePullPolicy: {{default "Always" .imagePullPolicy }}
        ports:
        - name: http
          containerPort: {{.containerPort }}
          protocol: TCP
        {{- if .env }}
        env:
        {{- toYaml .env | nindent 10}}
        {{- end}}
{{- end }}
