apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyI4MzgxMzQwNjczOTMuZGtyLmVjci5hcC1zb3V0aC0xLmFtYXpvbmF3cy5jb20iOnsidXNlcm5hbWUiOiJBV1MiLCJwYXNzd29yZCI6IiQoYXdzIGVjciBnZXQtbG9naW4tcGFzc3dvcmQpIiwiYXV0aCI6IlFWZFRPaVFvWVhkeklHVmpjaUJuWlhRdGJHOW5hVzR0Y0dGemMzZHZjbVFwIn19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
