{{- if .Values.secret }}
{{- if .Values.secret.enabled }}
{{- range .Values.secret.files }}
apiVersion: v1
kind: Secret
metadata:
  labels:
{{ toYaml $.Values.secret.additionalLabels | indent 4 }}
{{- if $.Values.secret.annotations }}
  annotations:
{{ toYaml $.Values.secret.annotations | indent 4 }}
{{- end }}
  {{- if contains "secret" .name }}
  name: {{ .name }}
  {{- else }}
  name: {{ .name }}-"secret"
  {{- end }}
type: {{default "Opaque" .type}}
data:
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
