apiVersion: v1
kind: Service
metadata:
  name: {{$.Values.name}}-service
spec:
  type: NodePort
  ports:
  - port: {{default "8000" $.Values.port}}
    targetPort: {{default "8000" $.Values.port}}
    nodePort: {{default "8000" $.Values.port}}
    protocol: TCP
  selector:
    app: {{$.Values.name}}
