{{ range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.nameOverride}}
  namespace: {{ default "default" .namespace }}
  labels:
    {{- include "mychart.labels" .labels | indent 4 }}
spec:
  type: {{ .type }}
  ports:
    - port: {{default .targetPort .port }}
      targetPort: {{default .port .targetPort }}
      {{- if ne .type "ClusterIP" }}
      nodePort: {{.nodePort}}
      {{- end}}
      protocol: {{ default "TCP" .protocol}}
      name: http
  selector:
    {{- include "mychart.labels" .labels | indent 4 }}
  {{- if eq .type "LoadBalancer" }}
  externalIPs: 
  - 127.0.0.1
  {{- end }} 
{{- end }}
